name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    - name: Deploy login
      uses: "actions/heroku@master"
      args: "container:login"
      secrets: ["HEROKU_API_KEY"]    
    - name: Deploy push
      uses: "actions/heroku@master"
      args: "container:push -a cleinly web"
      secrets: ["HEROKU_API_KEY"]    
    - name: Deploy release
      uses: "actions/heroku@master"
      args: "container:release -a cleinly web"
      secrets: ["HEROKU_API_KEY"]