name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    - name: Migrate
      run: npm run migrate:remote:up
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Deploy login
      uses: "actions/heroku@master"
      with:
        args: "container:login"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Deploy push
      uses: "actions/heroku@master"
      with:
        args: "container:push web"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Deploy release
      uses: "actions/heroku@master"
      with:
        args: "container:release web"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}